### ISSUE TITLE
Use data:latest to avoid outdated versions

### ISSUE THREAD

**Issue by mdelapenya** [wedeploy/boilerplate-data#10]

**Comment by zenorocha** [comment]
We have to think carefully about this. In the past we used latest images and latest SDK versions for all the docs and examples. That was good because most of the users were always on the latest versions. The problem was when we introduced a breaking change. It would break the examples, tutorials, and the users applications. That's why we switched to always declare a version next to the images and SDKs. Although it's convenient, I'm afraid this change can cause more problems than benefits.

**Comment by pragmaticivan** [comment]
@zenorocha for that we have CI for all the demos. We should just ensure we pay attention to that CI build.

**Comment by eduardolundgren** [comment]
we can't use latest because the server caches the version number

**Comment by eduardolundgren** [comment]
I am closing it because we can't clear the cache in an easy way in all workers with the registry
